export const apiRoutes = {
  agents: '/agents',
  similarity: '/agents/similarity',
  sources: '/agents/sources',
  specs: '/agents/specs',
  interpretSpec: '/agents/specs/interpret',
  spec: (specId: string) => `/agents/specs/${specId}`,
  specSection: (specId: string, section: 'outcomes' | 'knowledge' | 'guardrails' | 'outputs') =>
    `/agents/specs/${specId}/${section}`,
  generate: (specId: string) => `/agents/specs/${specId}/generate`,
  generationJob: (jobId: string) => `/agents/generation-jobs/${jobId}`,
  agent: (agentId: string) => `/agents/${agentId}`,
  recover: (agentId: string) => `/agents/${agentId}/recover`,
  shadowDeploy: (agentId: string) => `/agents/${agentId}/shadow-deploy`,
  evaluation: (agentId: string) => `/agents/${agentId}/evaluation`,
  certificationRuns: (agentId: string) => `/agents/${agentId}/certification-runs`,
  certificationRun: (runId: string) => `/agents/certification-runs/${runId}`,
  promote: (agentId: string) => `/agents/${agentId}/promote`,
  retire: (agentId: string) => `/agents/${agentId}/retire`,
  evalCases: '/agents/eval-cases',
  deactivateEvalCase: (caseId: string) => `/agents/eval-cases/${caseId}/deactivate`,
  publishEvalCorpus: '/agents/eval-corpus/publish',
  certificationGateConfigs: '/agents/certification-gate-configs',
  publishCertificationGateConfig: '/agents/certification-gate-configs/publish',
  health: '/health',
  openapi: '/openapi.json',
} as const;
