export const apiRoutes = {
  agents: '/agents',
  similarity: '/agents/similarity',
  sources: '/agents/sources',
  specs: '/agents/specs',
  interpretSpec: '/agents/specs/interpret',
  spec: (specId: string) => `/agents/specs/${specId}`,
  specSection: (specId: string, section: 'outcomes' | 'knowledge' | 'guardrails' | 'outputs') =>
    `/agents/specs/${specId}/${section}`,
  generate: (specId: string) => `/agents/specs/${specId}/generate`,
  generationJob: (jobId: string) => `/agents/generation-jobs/${jobId}`,
  agent: (agentId: string) => `/agents/${agentId}`,
  recover: (agentId: string) => `/agents/${agentId}/recover`,
  shadowDeploy: (agentId: string) => `/agents/${agentId}/shadow-deploy`,
  evaluation: (agentId: string) => `/agents/${agentId}/evaluation`,
  certificationRuns: (agentId: string) => `/agents/${agentId}/certification-runs`,
  certificationRun: (runId: string) => `/agents/certification-runs/${runId}`,
  promote: (agentId: string) => `/agents/${agentId}/promote`,
  retire: (agentId: string) => `/agents/${agentId}/retire`,
  evalCases: '/agents/eval-cases',
  deactivateEvalCase: (caseId: string) => `/agents/eval-cases/${caseId}/deactivate`,
  publishEvalCorpus: '/agents/eval-corpus/publish',
  certificationGateConfigs: '/agents/certification-gate-configs',
  publishCertificationGateConfig: '/agents/certification-gate-configs/publish',
  health: '/health',
  openapi: '/openapi.json',
} as const;

export const platformApiRoutes = {
  resources: '/v1/resources',
  repositoryImports: '/v1/repository-imports',
  releases: '/v1/releases',
  release: (releaseId: string) => `/v1/releases/${releaseId}`,
  authorityGrants: '/v1/authority-grants',
  revokeAuthorityGrant: (grantId: string) => `/v1/authority-grants/${grantId}/revoke`,
  executionRuns: '/v1/execution-runs',
  executionRun: (runId: string) => `/v1/execution-runs/${runId}`,
  approveExecutionRun: (runId: string) => `/v1/execution-runs/${runId}/approve`,
  cancelExecutionRun: (runId: string) => `/v1/execution-runs/${runId}/cancel`,
  outcomes: '/v1/outcomes',
  metrics: '/v1/metrics',
  releaseEvaluations: '/v1/release-evaluations',
  releaseEvaluation: (evaluationId: string) => `/v1/release-evaluations/${evaluationId}`,
  productionChannel: (channelKey: string) => `/v1/production-channels/${channelKey}`,
  promoteRelease: (channelKey: string) => `/v1/production-channels/${channelKey}/promote`,
  rollbackRelease: (channelKey: string) => `/v1/production-channels/${channelKey}/rollback`,
  automationSchedules: '/v1/automation-schedules',
  automationSchedule: (scheduleId: string) => `/v1/automation-schedules/${scheduleId}`,
  automationScheduleState: (scheduleId: string) => `/v1/automation-schedules/${scheduleId}/state`,
  scheduleDueAutomations: '/v1/automation-schedules/schedule-due',
  observations: '/v1/observations',
  improvementCandidates: '/v1/improvement-candidates',
  reviewImprovementCandidate: (candidateId: string) =>
    `/v1/improvement-candidates/${candidateId}/review`,
  memoryCandidates: '/v1/memory-candidates',
  reviewMemoryCandidate: (candidateId: string) => `/v1/memory-candidates/${candidateId}/review`,
} as const;
