{{- if .Values.serviceAccounts.backend.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "paul-os.backendServiceAccountName" . }}
  labels:
    {{- include "paul-os.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- with .Values.serviceAccounts.backend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccounts.backend.automountServiceAccountToken }}
{{- end }}
{{- if .Values.serviceAccounts.worker.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "paul-os.workerServiceAccountName" . }}
  labels:
    {{- include "paul-os.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  {{- with .Values.serviceAccounts.worker.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccounts.worker.automountServiceAccountToken }}
{{- end }}
{{- if .Values.serviceAccounts.migrator.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "paul-os.migratorServiceAccountName" . }}
  labels:
    {{- include "paul-os.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrator
  {{- with .Values.serviceAccounts.migrator.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccounts.migrator.automountServiceAccountToken }}
{{- end }}
